"""
Catalog BOM line definitions: purpose, quantity rules, overlaps, and proforma alignment.

Used by the API (BOM guide), ``bom_quantities``, and admin documentation.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

# category → display group
CATEGORIES = [
    "mounting",
    "dc_cabling",
    "ac_cabling",
    "battery_cabling",
    "dc_protection",
    "ac_protection",
    "distribution",
    "earthing",
    "consumables",
    "services",
]

CATALOG_BOM_ITEMS: Dict[str, Dict[str, Any]] = {
    "MNT-RAIL-SET-350": {
        "name": "Mounting rail set (priced per set)",
        "category": "mounting",
        "usage": "Roof rail segments + typical fixings per set — matches Ghana proforma 'Mounting Structure (Rails)'.",
        "qty_rule": "ceil(panels × 5/8), min 2 sets",
        "drivers": ["number_of_panels"],
        "proforma": True,
        "combines_with": "Use with BOS-PV-CLAMP-EA and BOS-ROOF-HOOK-EA; do not also bill MNT-RAIL-18FT unless rail_pricing_mode=sticks.",
        "essential": True,
    },
    "MNT-RAIL-18FT": {
        "name": "Mounting rail 18 ft (each stick)",
        "category": "mounting",
        "usage": "Individual aluminium rail sticks from sizing geometry (mounting_rails_estimate).",
        "qty_rule": "mounting_rails_estimate from sizing engine",
        "drivers": ["mounting_rails_estimate"],
        "proforma": False,
        "combines_with": "Alternative to MNT-RAIL-SET-350 — only one rail pricing mode should apply per quote.",
        "essential": False,
    },
    "BOS-ROOF-HOOK-EA": {
        "name": "Roof hook / L-foot (each)",
        "category": "mounting",
        "usage": "Anchors modules to roof structure; ~2 per panel on corrugated/metal roofs.",
        "qty_rule": "ceil(panels × bom_roof_hooks_per_panel), default 2",
        "drivers": ["number_of_panels"],
        "proforma": False,
        "combines_with": "Complements rail sets; omit if your rail set price already includes hooks.",
        "essential": True,
    },
    "BOS-PV-CLAMP-EA": {
        "name": "PV mid / end clamp (each)",
        "category": "mounting",
        "usage": "Secures modules to rails (mid + end clamps).",
        "qty_rule": "round(panels × bom_clamps_per_panel), default 3.5",
        "drivers": ["number_of_panels"],
        "proforma": True,
        "combines_with": None,
        "essential": True,
    },
    "CAB-PV-4MM-100M": {
        "name": "PV DC cable 4 mm² (100 m coil)",
        "category": "dc_cabling",
        "usage": "String homerun / interconnection for residential arrays (≤30 panels, ≤20 kW).",
        "qty_rule": "max(2, ceil(dc_string_count / 2)) coils",
        "drivers": ["dc_string_count", "system_size_kw"],
        "proforma": True,
        "combines_with": "Mutually exclusive with CAB-PV-6MM-100M per quote.",
        "essential": True,
    },
    "CAB-PV-6MM-100M": {
        "name": "PV DC cable 6 mm² (100 m coil)",
        "category": "dc_cabling",
        "usage": "Larger arrays / longer runs (>30 panels or >20 kW).",
        "qty_rule": "max(2, ceil(dc_string_count / 2)) coils",
        "drivers": ["dc_string_count", "number_of_panels", "system_size_kw"],
        "proforma": True,
        "combines_with": "Mutually exclusive with CAB-PV-4MM-100M per quote.",
        "essential": True,
    },
    "BOS-MC4-PAIR": {
        "name": "MC4 connector pair",
        "category": "dc_cabling",
        "usage": "DC plug connections at modules and string ends; ~1 pair per module interconnection.",
        "qty_rule": "ceil(panels × 1.2) pairs",
        "drivers": ["number_of_panels"],
        "proforma": False,
        "combines_with": "Was lumped in KIT-MISC-BOS; explicit line when bom_explicit_consumables=true.",
        "essential": True,
    },
    "CAB-RR10MM-100M": {
        "name": "RR 10 mm copper cable (100 m coil)",
        "category": "ac_cabling",
        "usage": "AC feeder from inverter to DB / changeover (heavy residential & commercial).",
        "qty_rule": "max(2, ceil(inverter_kW / 5)) coils",
        "drivers": ["inverter_size_kw", "inverter_count"],
        "proforma": True,
        "combines_with": None,
        "essential": True,
    },
    "CAB-AC-6MM-100M": {
        "name": "AC cable 6 mm² (100 m coil)",
        "category": "ac_cabling",
        "usage": "Branch AC wiring, DB to loads (smaller runs); supplements RR10 where needed.",
        "qty_rule": "1 coil if inverter ≤10 kW else ceil(inverter_kW/10)",
        "drivers": ["inverter_size_kw"],
        "proforma": False,
        "combines_with": "Complements CAB-RR10MM-100M, not a substitute.",
        "essential": False,
    },
    "CAB-BATT-35MM-M": {
        "name": "Battery cable 35 mm² (per metre)",
        "category": "battery_cabling",
        "usage": "Battery interconnect and inverter–battery DC runs (hybrid/off-grid).",
        "qty_rule": "~2 m per kWh (small bank) or supplementary on large banks",
        "drivers": ["battery_capacity_kwh"],
        "proforma": True,
        "combines_with": "With CAB-BATT-50MM-M on banks ≥15 kWh",
        "essential": True,
    },
    "CAB-BATT-50MM-M": {
        "name": "Battery cable 50 mm² (per metre)",
        "category": "battery_cabling",
        "usage": "Main battery bank feeders (≥15 kWh).",
        "qty_rule": "~0.9 m per kWh",
        "drivers": ["battery_capacity_kwh"],
        "proforma": True,
        "combines_with": None,
        "essential": False,
    },
    "PRT-DC63-2P": {
        "name": "63 A DC MCB 2-pole",
        "category": "dc_protection",
        "usage": "DC string / combiner protection (one per string group).",
        "qty_rule": "max(min_dc_breakers, dc_string_count)",
        "drivers": ["dc_string_count", "system_type"],
        "proforma": True,
        "combines_with": "Works with BOS-DC-ISO-32A (isolator before breaker).",
        "essential": True,
    },
    "BOS-DC-ISO-32A": {
        "name": "DC isolator switch 32 A",
        "category": "dc_protection",
        "usage": "Lockable DC disconnect for maintenance — typically one per string or per inverter DC input.",
        "qty_rule": "max(1, dc_string_count)",
        "drivers": ["dc_string_count"],
        "proforma": False,
        "combines_with": "One per string; not duplicated by PRT-DC63-2P (breaker vs isolator).",
        "essential": True,
    },
    "PRT-AC100-1P": {
        "name": "100 A AC breaker",
        "category": "ac_protection",
        "usage": "AC overcurrent protection at DB / inverter output.",
        "qty_rule": "1–2 by inverter count; +1 main when total inverter >8 kW",
        "drivers": ["inverter_size_kw", "inverter_count"],
        "proforma": True,
        "combines_with": "PRT-AC125-1P on larger systems (main + branch).",
        "essential": True,
    },
    "PRT-AC125-1P": {
        "name": "125 A AC breaker",
        "category": "ac_protection",
        "usage": "Higher-rated AC protection when total inverter >8 kW.",
        "qty_rule": "1 when total inverter >8 kW",
        "drivers": ["inverter_size_kw", "inverter_count"],
        "proforma": True,
        "combines_with": "Used with PRT-AC100-1P on same quote (proforma Option 2).",
        "essential": False,
    },
    "PRT-CO-100A": {
        "name": "100 A manual changeover",
        "category": "ac_protection",
        "usage": "Grid / generator / inverter selection (hybrid & backup).",
        "qty_rule": "1 per inverter",
        "drivers": ["inverter_count"],
        "proforma": True,
        "combines_with": "Skip for pure grid-tied with no backup if bom_skip_changeover_grid_tied=true.",
        "essential": True,
    },
    "BOS-AC-ISO-40A": {
        "name": "AC isolator 40 A",
        "category": "ac_protection",
        "usage": "AC side disconnect at inverter for safe maintenance.",
        "qty_rule": "1 per inverter",
        "drivers": ["inverter_count"],
        "proforma": False,
        "combines_with": None,
        "essential": True,
    },
    "BOX-DB-6WAY": {
        "name": "6-way distribution board",
        "category": "distribution",
        "usage": "Small AC distribution enclosure.",
        "qty_rule": "1 per system",
        "drivers": [],
        "proforma": True,
        "combines_with": "BOX-DB-13WAY for larger breaker counts.",
        "essential": True,
    },
    "BOX-DB-13WAY": {
        "name": "13-way distribution board",
        "category": "distribution",
        "usage": "Main AC DB for breakers, SPD, and feeds.",
        "qty_rule": "scales with inverter count + DC strings / system kW",
        "drivers": ["inverter_count", "dc_string_count", "system_size_kw"],
        "proforma": True,
        "combines_with": None,
        "essential": True,
    },
    "PRT-SPD-500V": {
        "name": "DC/DC SPD 500 V class",
        "category": "dc_protection",
        "usage": "Lightning / surge protection on DC side (standard residential).",
        "qty_rule": "1 when system <30 kW and panels ≤40",
        "drivers": ["system_size_kw", "number_of_panels"],
        "proforma": True,
        "combines_with": "Mutually exclusive with PRT-SPD-1000V per quote.",
        "essential": True,
    },
    "PRT-SPD-1000V": {
        "name": "DC/DC SPD 1000 V class",
        "category": "dc_protection",
        "usage": "Higher-voltage SPD for large arrays.",
        "qty_rule": "1 when system ≥30 kW or panels >40",
        "drivers": ["system_size_kw", "number_of_panels"],
        "proforma": True,
        "combines_with": "Mutually exclusive with PRT-SPD-500V per quote.",
        "essential": False,
    },
    "PRT-MCCB-250A": {
        "name": "250 A MCCB (battery main)",
        "category": "battery_cabling",
        "usage": "Battery bank main overcurrent protection.",
        "qty_rule": "max(2, 2×ceil(kWh/20))",
        "drivers": ["battery_capacity_kwh"],
        "proforma": True,
        "combines_with": "Hybrid/off-grid only when battery_kwh > 0.",
        "essential": True,
    },
    "BOS-EARTH-KIT": {
        "name": "Earthing kit (rod, clamp, 16 mm earth cable)",
        "category": "earthing",
        "usage": "Equipment bonding and array grounding per local wiring rules.",
        "qty_rule": "1 base + 1 per ceil(panels/16)",
        "drivers": ["number_of_panels"],
        "proforma": False,
        "combines_with": None,
        "essential": True,
    },
    "BOS-TRUNK-25MM-M": {
        "name": "PVC trunking 25 mm (per metre)",
        "category": "consumables",
        "usage": "Cable management for AC/DC runs on wall/facade.",
        "qty_rule": "ceil(panels × 1.5) metres",
        "drivers": ["number_of_panels"],
        "proforma": False,
        "combines_with": "Partially overlapped by KIT-MISC-BOS — explicit take-off when bom_explicit_consumables=true.",
        "essential": False,
    },
    "BOS-LABEL-KIT": {
        "name": "DC/AC labeling & warning kit",
        "category": "consumables",
        "usage": "Circuit labels, arc-flash / DC warning stickers for commissioning sign-off.",
        "qty_rule": "1 per system",
        "drivers": [],
        "proforma": False,
        "combines_with": None,
        "essential": True,
    },
    "KIT-MISC-BOS": {
        "name": "Miscellaneous consumables (standard)",
        "category": "consumables",
        "usage": "Glands, lugs, cable ties, small fixings not itemized separately.",
        "qty_rule": "1 lot; systems ≤30 panels / ≤20 kW",
        "drivers": ["system_size_kw", "number_of_panels"],
        "proforma": True,
        "combines_with": "When bom_explicit_consumables=true, MC4/trunking/labels are separate; misc is reduced catch-all.",
        "essential": True,
    },
    "KIT-MISC-BOS-L": {
        "name": "Miscellaneous consumables (large)",
        "category": "consumables",
        "usage": "Same as KIT-MISC-BOS for commercial-scale jobs.",
        "qty_rule": "1 lot; >30 panels or >20 kW",
        "drivers": ["system_size_kw", "number_of_panels"],
        "proforma": True,
        "combines_with": None,
        "essential": True,
    },
    "SRV-TRANSPORT-STD": {
        "name": "Transport & logistics",
        "category": "services",
        "usage": "Delivery of equipment to site (Ghana proforma reference).",
        "qty_rule": "1 per quote",
        "drivers": [],
        "proforma": True,
        "combines_with": None,
        "essential": True,
    },
    "SRV-INSTALL-6000": {
        "name": "Installation & commissioning (standard)",
        "category": "services",
        "usage": "Labour, testing, handover — tier ≤25 kW.",
        "qty_rule": "1 when system_size_kw ≤25",
        "drivers": ["system_size_kw"],
        "proforma": True,
        "combines_with": "Mutually exclusive install SKU tier with SRV-INSTALL-8000.",
        "essential": True,
    },
    "SRV-INSTALL-8000": {
        "name": "Installation & commissioning (large)",
        "category": "services",
        "usage": "Labour for larger arrays (>25 kW).",
        "qty_rule": "1 when system_size_kw >25",
        "drivers": ["system_size_kw"],
        "proforma": True,
        "combines_with": None,
        "essential": False,
    },
}

# Items commonly required on site but not yet auto-quoted (add manually or future SKU)
RECOMMENDED_MANUAL_LINES: List[Dict[str, str]] = [
    {
        "item": "Engineering / design drawings",
        "reason": "String layout, single-line diagram, load study — not auto-generated.",
    },
    {
        "item": "ECG / utility application fees",
        "reason": "Grid-tied export or net-metering approvals vary by region.",
    },
    {
        "item": "Scaffolding / height access",
        "reason": "Multi-storey or steep roof — site-specific.",
    },
    {
        "item": "Concrete ballast / ground mount civils",
        "reason": "Ground-mount only; not in roof-mount BOM.",
    },
    {
        "item": "Generator integration panel",
        "reason": "Add when changeover feeds existing gen set beyond standard CO.",
    },
    {
        "item": "Monitoring / Wi-Fi dongle",
        "reason": "Inverter brand-specific; add from equipment catalog.",
    },
]


def catalog_bom_usage_for_api() -> Dict[str, Any]:
    """Structured payload for GET /quotes/bom-rules-reference."""
    by_category: Dict[str, List[Dict[str, Any]]] = {c: [] for c in CATEGORIES}
    for sku, meta in CATALOG_BOM_ITEMS.items():
        cat = meta.get("category", "consumables")
        if cat not in by_category:
            by_category[cat] = []
        by_category[cat].append({"sku": sku, **meta})

    return {
        "categories": CATEGORIES,
        "items_by_category": by_category,
        "all_skus": list(CATALOG_BOM_ITEMS.keys()),
        "recommended_manual_lines": RECOMMENDED_MANUAL_LINES,
        "overlap_notes": [
            "Rail pricing: use either MNT-RAIL-SET-350 (proforma sets) OR MNT-RAIL-18FT (stick count), controlled by setting bom_rail_pricing_mode.",
            "PV cable: only 4 mm or 6 mm coil per quote, chosen by array size.",
            "SPD: only 500 V or 1000 V class per quote.",
            "Explicit consumables (MC4, isolators, earth, labels) split out when bom_explicit_consumables=true; misc kit is then a smaller catch-all.",
        ],
    }
