"""change_appliance_enums_to_strings

Revision ID: 304a25b97468
Revises: feb357a15984
Create Date: 2025-11-27 10:42:31.399319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '304a25b97468'
down_revision = 'feb357a15984'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appliances', 'category',
               existing_type=postgresql.ENUM('LIGHTING', 'COOLING', 'HEATING', 'COOKING', 'REFRIGERATION', 'LAUNDRY', 'ENTERTAINMENT', 'COMPUTING', 'WATER_HEATING', 'WATER_PUMPING', 'VENTILATION', 'SECURITY', 'MEDICAL', 'INDUSTRIAL', 'COMMERCIAL', 'OTHER', name='appliancecategory'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('appliances', 'appliance_type',
               existing_type=postgresql.ENUM('LIGHTING', 'FRIDGE', 'FAN', 'AC', 'PUMP', 'OTHER', 'tv_42inch_led', 'ps5', 'ps4', 'xbox_series_x', 'monitor_24inch', 'printer_small', 'printer_large', name='appliancetype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appliances', 'appliance_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LIGHTING', 'FRIDGE', 'FAN', 'AC', 'PUMP', 'OTHER', 'tv_42inch_led', 'ps5', 'ps4', 'xbox_series_x', 'monitor_24inch', 'printer_small', 'printer_large', name='appliancetype'),
               existing_nullable=False)
    op.alter_column('appliances', 'category',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LIGHTING', 'COOLING', 'HEATING', 'COOKING', 'REFRIGERATION', 'LAUNDRY', 'ENTERTAINMENT', 'COMPUTING', 'WATER_HEATING', 'WATER_PUMPING', 'VENTILATION', 'SECURITY', 'MEDICAL', 'INDUSTRIAL', 'COMMERCIAL', 'OTHER', name='appliancecategory'),
               existing_nullable=False)
    # ### end Alembic commands ###

