"""add_appliance_category

Revision ID: 79c9baf6500d
Revises: 
Create Date: 2025-11-26 21:23:08.606167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c9baf6500d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appliances', sa.Column('category', sa.Enum('LIGHTING', 'COOLING', 'HEATING', 'COOKING', 'REFRIGERATION', 'LAUNDRY', 'ENTERTAINMENT', 'COMPUTING', 'WATER_HEATING', 'WATER_PUMPING', 'VENTILATION', 'SECURITY', 'MEDICAL', 'INDUSTRIAL', 'COMMERCIAL', 'OTHER', name='appliancecategory'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appliances', 'category')
    # ### end Alembic commands ###

